### ISSUE TITLE
It's not possible to upload more than 1 csv

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#13]
If I try to add a second set I always get the "cannot insert dataset, already exists" error:

```
ubuntu@ip-172-31-18-156:~/spot/data$ sudo docker exec -ti spot-server /spot/spot_init.py -i \
>     --table spot_data \
>     --file /data/fgl3.csv \
>     --name '3FGL_Fermi_catalog' \
>     --description '3FGL gamma ray source catalog' \
>     --session /data/data_prod.json
fgl3
Traceback (most recent call last):
  File "/spot/spot_init.py", line 119, in <module>
    uploadCSV(tableName=table_name, fileName=file_name, columnName='dataset', columnVal=dataset_name)
  File "/spot/spot_init.py", line 17, in uploadCSV
    df.insert(0, columnName, f'"{columnVal}"')
  File "/usr/lib/python3.7/site-packages/pandas/core/frame.py", line 3591, in insert
    self._data.insert(loc, column, value, allow_duplicates=allow_duplicates)
  File "/usr/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1173, in insert
    raise ValueError("cannot insert {}, already exists".format(item))
ValueError: cannot insert dataset, already exists
```

I can the same error with a different dataset:

```
ubuntu@ip-172-31-18-156:~/spot$ sudo docker exec -ti spot-server /spot/spot_init.py -i \
>     --table spot_data \
>     --file /data/ewkinos.csv \
>     --name 'EWkinos' \
>     --description 'EWKinos exclusion' \
>     --session /data/data_prod.json
  ewkinos
  Traceback (most recent call last):
  File "/spot/spot_init.py", line 119, in <module>
    uploadCSV(tableName=table_name, fileName=file_name, columnName='dataset', columnVal=dataset_name)
  File "/spot/spot_init.py", line 17, in uploadCSV
    df.insert(0, columnName, f'"{columnVal}"')
  File "/usr/lib/python3.7/site-packages/pandas/core/frame.py", line 3591, in insert
     self._data.insert(loc, column, value, allow_duplicates=allow_duplicates)
  File "/usr/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1173, in insert
    raise ValueError("cannot insert {}, already exists".format(item))
ValueError: cannot insert dataset, already exists
```

I have tried to change the session file, the table name, etc. But I always get that error after I added a first dataset (in this case it was the MSSM GC Excess dataset).

I think this line in spot_init.py:
`uploadCSV(tableName=table_name, fileName=file_name, columnName='dataset', columnVal=dataset_name)`

Shouldn't the columnName be a variable instead of hardcoded to always be "dataset"?

**Comment by fdiblen** [comment]
When you add a csv file, the Python script adds extra column named 'dataset'. Please make sure that you don't have this column in your csv file before uploading the file.

**Comment by l-hendriks** [comment]
works when I remove it
