### ISSUE TITLE
column "source_name" of relation "spot_data" does not exist

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#14]
Do you know what this error means?

I get this when I try to upload the fgl3 csv file...

```
ubuntu@ip-172-31-18-156:~/spot$ sudo docker exec -ti spot-server /spot/spot_init.py -i --table spot_data --file /data/fgl3.csv --name 'FGL3' --description 'Fermi FGL3 point source catalog' --session /data/data_testing.json
fgl3
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1229, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 854, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.ProgrammingError: column "source_name" of relation "spot_data" does not exist
LINE 1: INSERT INTO spot_data (index, dataset, source_name, class1, ...
                                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/spot/spot_init.py", line 119, in <module>
    uploadCSV(tableName=table_name, fileName=file_name, columnName='dataset', columnVal=dataset_name)
  File "/spot/spot_init.py", line 19, in uploadCSV
    df.to_sql(tableName, con=pg_engine, if_exists='append')
  File "/usr/lib/python3.7/site-packages/pandas/core/generic.py", line 2712, in to_sql
    method=method,
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 518, in to_sql
    method=method,
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 1320, in to_sql
    table.insert(chunksize, method=method)
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 756, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 670, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1229, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 854, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "source_name" of relation "spot_data" does not exist
LINE 1: INSERT INTO spot_data (index, dataset, source_name, class1, ...
                                               ^

[SQL: INSERT INTO spot_data (index, dataset, source_name, class1, flux1000_3000, flux100_300, flux3000_10000, flux300_1000, flux_density, glat, signif_curve, spectral_index, unc_energy_flux100, variability_index) VALUES (%(index)s, %(dataset)s, %(source_name)s, %(class1)s, %(flux1000_3000)s, %(flux100_300)s, %(flux3000_10000)s, %(flux300_1000)s, %(flux_density)s, %(glat)s, %(signif_curve)s, %(spectral_index)s, %(unc_energy_flux100)s, %(variability_index)s)]
[parameters: ({'index': 0, 'dataset': '"fgl3"', 'source_name': '3FGL J0000.1+6545 ', 'class1': 'UND  ', 'flux1000_3000': 0.04465416073799133, 'flux100_300': 0.2773666977882385, 'flux3000_10000': 0.3294320106506348, 'flux300_1000': 0.15122932195663452, 'flux_density': 0.4543376668126546, 'glat': 0.5300611356993397, 'signif_curve': 0.3324705845731934, 'spectral_index': 2.410955905914306, 'unc_energy_flux100': 0.3846190163217038, 'variability_index': 0.3388134021873827}, {'index': 1, 'dataset': '"fgl3"', 'source_name': '3FGL J0000.2-3738 ', 'class1': 'UND  ', 'flux1000_3000': 0.3393433094024658, 'flux100_300': 0.5761430263519287, 'flux3000_10000': 0.175913006067276, 'flux300_1000': 0.5194154977798462, 'flux_density': 0.22376289304169888, 'glat': 0.016860357155052963, 'signif_curve': 0.20540314572558427, 'spectral_index': 1.866731882095337, 'unc_energy_flux100': 0.1069079407149367, 'variability_index': 0.3473014225891659}, {'index': 2, 'dataset': '"fgl3"', 'source_name': '3FGL J0001.0+6314 ', 'class1': 'spp  ', 'flux1000_3000': 0.2772244215011597, 'flux100_300': 0.1376751959323883, 'flux3000_10000': 0.01715219020843506, 'flux300_1000': 0.060991644859313965, 'flux_density': 0.5799013607391492, 'glat': 0.5084314650201708, 'signif_curve': 0.051249202837588326, 'spectral_index': 2.732785940170288, 'unc_energy_flux100': 0.3613314410121662, 'variability_index': 0.36224538158354985}, {'index': 3, 'dataset': '"fgl3"', 'source_name': '3FGL J0001.2-0748 ', 'class1': 'bll  ', 'flux1000_3000': 0.2874290347099304, 'flux100_300': 0.337669312953949, 'flux3000_10000': 0.04555809497833252, 'flux300_1000': 0.2004433870315552, 'flux_density': 0.4117995026882235, 'glat': 0.03838062224042976, 'signif_curve': 0.2390625996631047, 'spectral_index': 2.1493482589721684, 'unc_energy_flux100': 0.19149734702967253, 'variability_index': 0.35650822559745793}, {'index': 4, 'dataset': '"fgl3"', 'source_name': '3FGL J0001.4+2120 ', 'class1': 'fsrq ', 'flux1000_3000': 2.089142799377441e-05, 'flux100_300': 0.19279253482818606, 'flux3000_10000': 0.5517441034317017, 'flux300_1000': 0.08921557664871216, 'flux_density': 0.6425898782495807, 'glat': 0.17820745175365948, 'signif_curve': 0.379186803895389, 'spectral_index': 2.3051133155822754, 'unc_energy_flux100': 0.16175668871847204, 'variability_index': 0.44285818673979066}, {'index': 5, 'dataset': '"fgl3"', 'source_name': '3FGL J0001.6+3535 ', 'class1': 'UND  ', 'flux1000_3000': 0.1869923174381256, 'flux100_300': 0.038799136877059937, 'flux3000_10000': 0.3593764901161194, 'flux300_1000': 0.3129187822341919, 'flux_density': 0.3811586101163167, 'glat': 0.2793875256978038, 'signif_curve': 0.030751948078845768, 'spectral_index': 2.3505215644836426, 'unc_energy_flux100': 0.1479665750535144, 'variability_index': 0.3185307355761341}, {'index': 6, 'dataset': '"fgl3"', 'source_name': '3FGL J0002.0-6722 ', 'class1': 'UND  ', 'flux1000_3000': 0.28887778520584106, 'flux100_300': 0.5457645654678345, 'flux3000_10000': 0.2510349750518799, 'flux300_1000': 0.23862528800964355, 'flux_density': 0.2769885744720231, 'glat': 0.1221335677658122, 'signif_curve': 0.19360919841676744, 'spectral_index': 1.946061372756958, 'unc_energy_flux100': 0.1379856979787899, 'variability_index': 0.3498009582848144}, {'index': 7, 'dataset': '"fgl3"', 'source_name': '3FGL J0002.2-4152 ', 'class1': 'bcu  ', 'flux1000_3000': 0.5337346196174622, 'flux100_300': 0.0963049829006195, 'flux3000_10000': 0.2096969187259674, 'flux300_1000': 0.13096731901168826, 'flux_density': 0.3013132179752553, 'glat': 0.0238003262532186, 'signif_curve': 0.040985039136311005, 'spectral_index': 2.0889208316802983, 'unc_energy_flux100': 0.10719583420035583, 'variability_index': 0.3676312386694972}  ... displaying 10 of 3034 total bound parameter sets ...  {'index': 3032, 'dataset': '"fgl3"', 'source_name': '3FGL J2359.3-3038 ', 'class1': 'bll  ', 'flux1000_3000': 0.2248091995716095, 'flux100_300': 0.13761544227600098, 'flux3000_10000': 0.3053573966026306, 'flux300_1000': 0.2623138427734375, 'flux_density': 0.3301552178505187, 'glat': 0.010494179475597498, 'signif_curve': 0.10402856274101496, 'spectral_index': 2.0215902328491206, 'unc_energy_flux100': 0.18494089863141827, 'variability_index': 0.3392764764727089}, {'index': 3033, 'dataset': '"fgl3"', 'source_name': '3FGL J2359.5-2052 ', 'class1': 'bll  ', 'flux1000_3000': 0.2288469076156616, 'flux100_300': 0.10966497659683228, 'flux3000_10000': 0.4799492955207825, 'flux300_1000': 0.2615968585014343, 'flux_density': 0.2902442462428305, 'glat': 0.013285918511696082, 'signif_curve': 0.028480365519626787, 'spectral_index': 2.0176827907562256, 'unc_energy_flux100': 0.1344356095235586, 'variability_index': 0.3285546975455977})]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by fdiblen** [comment]
Can you check if spot_data table exists?
I will need more details about the database and steps to reproduce the issue.

**Comment by l-hendriks** [comment]
Yes the spot_data table exists. Anyway, I'm going to completely terminate the server, start a new one and try again with the same dataset. See if that works, will let you know!

**Comment by fdiblen** [comment]
@l-hendriks any updates on this? I will need your input to close this issue.

**Comment by doc-l2** [comment]
I managed to upload the FGL3 data after creating this issue, so I think a newer version solved it already. Closing.
