### ISSUE TITLE
How much memory does the import script consume?

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#15]
My virtual server has 512MB of memory (this is a server that is in the free tier), but when I try to import the ewkinos.csv dataset I get a memory error:

```
ubuntu@ip-172-31-18-156:~/spot$ sudo docker exec -ti spot-server /spot/spot_init.py -i --table spot_data --file /data/ewkinos.csv --name 'EWkinos' --description 'EWKinos exclusion' --session /data/data_testing.json
 ewkinos
                  Traceback (most recent call last):
  File "/spot/spot_init.py", line 119, in <module>
    uploadCSV(tableName=table_name, fileName=file_name, columnName='dataset', columnVal=dataset_name)
  File "/spot/spot_init.py", line 19, in uploadCSV
    df.to_sql(tableName, con=pg_engine, if_exists='append')
  File "/usr/lib/python3.7/site-packages/pandas/core/generic.py", line 2712, in to_sql
    method=method,
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 518, in to_sql
    method=method,
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 1320, in to_sql
    table.insert(chunksize, method=method)
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 756, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 669, in _execute_insert
    data = [dict(zip(keys, row)) for row in data_iter]
  File "/usr/lib/python3.7/site-packages/pandas/io/sql.py", line 669, in <listcomp>
    data = [dict(zip(keys, row)) for row in data_iter]
MemoryError
```

The dataset is only 71MB. What is the minimum required RAM for spot? If I get a bigger server I have to start paying, so want to use a server that is higher than the minimum but as low as possible.

**Comment by fdiblen** [comment]
fixed by e8dcd3c3e999660ba760b4c5a12079bc185da932
Please reopen if you have more issues.
