### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#16]
Cannot add a dataset. This is what I did:

1. Create a virtual server (so this is from a fresh install)
2. Install docker and docker-compose
3. Run docker-compose yml file
4. Upload the csv file to the data folder (this worked before)
5. Run the following script while docker-compose runs:

```
sudo docker exec -ti spot-server /spot/spot_init.py -i \
>     --table spot_data \
>     --file /data/150205703.csv \
>     --name 'mssm_gc_excess' \
>     --description 'Dataset from "A description of the Galactic Center excess in the Minimal Supersymmetric Standard Model"' \
>     --session /data/session.json
```

The csv file is the same 150205703.csv as I'm always using and has no dataset column.

This is the error:

```
ubuntu@ip-172-31-39-93:~/spot$ sudo docker exec -ti spot-server /spot/spot_init.py -i     --table spot_data     --file /data/150205703.csv     --name 'mssm_gc_excess'     --description 'Dataset from "A description of the Galactic Center excess in the Minimal Supersymmetric Standard Model"'     --session /data/session.json
150205703
/spot/spot-server/node_modules/crossfilter2/src/index.js:1
import xfilterArray from './array';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/spot/spot-server/node_modules/spot-framework/src/dataview.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

**Comment by fdiblen** [comment]
@l-hendriks Can you please provide a small dataset to reproduce the issue?

**Comment by doc-l2** [comment]
Hi Faruk, this is a very old issue. After Nov last year I got SPOT working, so I don't think this is an issue anymore. Closing.
