### ISSUE TITLE
Sometimes the server crashes

### ISSUE THREAD

**Issue by doc-l2** [NLeSC/spot-server#18]
Not sure how to reproduce, but if you make some histograms using "Standard model" and process id plus a couple of others, at some point you get an empty histogram and the server crashes with this error:

```
/spot/spot-server/src/sql-driver.js:798
    var subFacet = dataset.facets.get(partition.facetName, 'name');
                           ^

TypeError: Cannot read property 'facets' of undefined
    at /spot/spot-server/src/sql-driver.js:798:28
    at Array.forEach (<anonymous>)
    at child.Collection.<computed> (/spot/spot-server/node_modules/ampersand-collection/ampersand-collection.js:390:36)
    at subTableQuery (/spot/spot-server/src/sql-driver.js:795:28)
    at /spot/spot-server/src/sql-driver.js:924:20
    at Array.forEach (<anonymous>)
    at Object.getData (/spot/spot-server/src/sql-driver.js:922:23)
    at /spot/spot-server/src/main.js:104:36
    at Array.forEach (<anonymous>)
    at child.Collection.<computed> (/spot/spot-server/node_modules/ampersand-collection/ampersand-collection.js:390:36)
```

**Comment by doc-l2** [comment]
this is the full error:

```
faecb676-2843-f01d-405a-a756b8a28368: SELECT a AS a, sum(count) AS count FROM (SELECT LEAST(WIDTH_BUCKET(e1::real, array[0, 141292.5, 282585, 423877.5, 565170, 706462.5, 847755, 989047.5, Sat Dec 06 1130 00:00:00 GMT+0000, 1271632.5, 1412925, 1554217.5, 1695510, 1836802.5, Wed Apr 05 1978 00:00:00 GMT+0000, 2119387.5, 2260680, 2401972.5, Sun Sep 22 2543 00:00:00 GMT+0000, 2684557.5, 2825850]::real[]) - 1, 19) AS a, COUNT(1) AS count FROM spot_data WHERE (e1 IS NOT NULL) AND (e1>=0 AND e1<=2825850) GROUP BY a UNION ALL (SELECT LEAST(WIDTH_BUCKET(e1::real, array[0, 141292.5, 282585, 423877.5, 565170, 706462.5, 847755, 989047.5, Sat Dec 06 1130 00:00:00 GMT+0000, 1271632.5, 1412925, 1554217.5, 1695510, 1836802.5, Wed Apr 05 1978 00:00:00 GMT+0000, 2119387.5, 2260680, 2401972.5, Sun Sep 22 2543 00:00:00 GMT+0000, 2684557.5, 2825850]::real[]) - 1, 19) AS a, COUNT(1) AS count FROM spot_data WHERE (e1 IS NOT NULL) AND (e1>=0 AND e1<=2825850) GROUP BY a)) AS datasetUnion GROUP BY a ORDER BY a ASC
error running query Error: ERROR:  syntax error at or near "Dec"
LINE 1: ...423877.5, 565170, 706462.5, 847755, 989047.5, Sat Dec 06 113...
                                                             ^

    at module.exports.Client._readError (/spot/spot-server/node_modules/pg-native/index.js:80:13)
    at module.exports.Client._read (/spot/spot-server/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:310:20) {
  severity: 'ERROR',
  sqlState: '42601',
  messagePrimary: 'syntax error at or near "Dec"',
  statementPosition: '208',
  sourceFile: 'scan.l',
  sourceLine: '1150',
  sourceFunction: 'scanner_yyerror'
}
(node:1183) UnhandledPromiseRejectionWarning: Error: Cannot finish getData: Cannot get data:Error: ERROR:  syntax error at or near "Dec"
LINE 1: ...423877.5, 565170, 706462.5, 847755, 989047.5, Sat Dec 06 113...
                                                             ^

    at /spot/spot-server/src/main.js:113:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Client requests: disconnect
Connecting to client
Connecting to client
/spot/spot-server/src/sql-driver.js:798
    var subFacet = dataset.facets.get(partition.facetName, 'name');
                           ^

TypeError: Cannot read property 'facets' of undefined
    at /spot/spot-server/src/sql-driver.js:798:28
    at Array.forEach (<anonymous>)
    at child.Collection.<computed> (/spot/spot-server/node_modules/ampersand-collection/ampersand-collection.js:390:36)
    at subTableQuery (/spot/spot-server/src/sql-driver.js:795:28)
    at /spot/spot-server/src/sql-driver.js:924:20
    at Array.forEach (<anonymous>)
    at Object.getData (/spot/spot-server/src/sql-driver.js:922:23)
    at /spot/spot-server/src/main.js:104:36
    at Array.forEach (<anonymous>)
    at child.Collection.<computed> (/spot/spot-server/node_modules/ampersand-collection/ampersand-collection.js:390:36)
```

**Comment by doc-l2** [comment]
Steps to reproduce:

- Open http://spot.phenomldata.org
- Select both sm and gluino dataset
- Create histogram of e1
- You don't see the histogram (because of the error)

If you only select 1 dataset it does work
