### ISSUE TITLE
Importing csv with spot-import does not work

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#7]
This is the error:

```/spot-server/node_modules/spot-framework/src/driver/server.js:31
  spot.socket.emit('scanData', {
              ^

TypeError: Cannot read property 'emit' of undefined
    at Object.scan (/spot-server/node_modules/spot-framework/src/driver/server.js:31:15)
    at child.scan (/spot-server/node_modules/spot-framework/src/dataset.js:106:17)
    at uploadDataset (/spot-server/scripts/spot-import.js:179:11)
    at /spot-server/scripts/spot-import.js:169:7
    at Parser.<anonymous> (/spot-server/node_modules/csv-parse/lib/index.js:104:16)
    at emitNone (events.js:111:20)
    at Parser.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I always get this error, but can "fix" it by going to `server.js` and changing the `scan` function to 

```function scan (dataset) {
  return;
}```

effectively removing this functionality. I have no idea what I broke, as everything still works, but now I can add datasets.

**Comment by fdiblen** [comment]
fixed in latest dev version.
