### ISSUE TITLE
Table name cannot start with a number, nor contain a dot

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#9]
The error you get if you add something with the name "v1501.02003" is:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

error: syntax error at or near ".02003"
    at Connection.parseE (/spot-server/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/spot-server/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/spot-server/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
```

It would be nice if there was some preprocessing that catches this and throws an error that's helpful.

**Comment by fdiblen** [comment]
This is a limitation in PG due to naming standards.
